@startuml data_pipeline
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title Data Pipeline - Diagramas
footer Disponível em: https://github.com/acnaweb/mackenzie

LAYOUT_LANDSCAPE()

Person(user, "Usuário")

System_Boundary(olap, "OLAP") {
        Container(ia, "ML/IA", "Tensor Flow/Sklearning", "")
}


@enduml